"""empty message

Revision ID: 29cde32fe913
Revises:
Create Date: 2021-06-26 13:41:35.165482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cde32fe913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'category',
        'questions',
        'categories',
        ['category'],
        ['id'],
        onupdate='CASCADE',
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###
