"""empty message

Revision ID: b305a0237bd0
Revises: 29cde32fe913
Create Date: 2021-06-26 13:42:15.819912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b305a0237bd0'
down_revision = '29cde32fe913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'questions',
        sa.Column('category_id', sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        'questions',
        'categories',
        ['category_id'],
        ['id'],
    )
    questions = sa.table(
        'questions',
        sa.column('category'),
        sa.column('category_id'),
    )
    op.execute(
        sa.update(questions).
        where(questions.columns.category_id == sa.null()).
        values(category_id=questions.columns.category)
    )
    op.alter_column('questions', 'category_id', nullable=False)
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'questions',
        sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
